/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  WishList, // @ts-ignore
  Listing, // @ts-ignore
  User,
} from "@prisma/client";

export class WishListServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.WishListCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.WishListCountArgs>
  ): Promise<number> {
    return this.prisma.wishList.count(args);
  }

  async wishLists<T extends Prisma.WishListFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.WishListFindManyArgs>
  ): Promise<WishList[]> {
    return this.prisma.wishList.findMany(args);
  }
  async wishList<T extends Prisma.WishListFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WishListFindUniqueArgs>
  ): Promise<WishList | null> {
    return this.prisma.wishList.findUnique(args);
  }
  async createWishList<T extends Prisma.WishListCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WishListCreateArgs>
  ): Promise<WishList> {
    return this.prisma.wishList.create<T>(args);
  }
  async updateWishList<T extends Prisma.WishListUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WishListUpdateArgs>
  ): Promise<WishList> {
    return this.prisma.wishList.update<T>(args);
  }
  async deleteWishList<T extends Prisma.WishListDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.WishListDeleteArgs>
  ): Promise<WishList> {
    return this.prisma.wishList.delete(args);
  }

  async getListing(parentId: string): Promise<Listing | null> {
    return this.prisma.wishList
      .findUnique({
        where: { id: parentId },
      })
      .listing();
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.wishList
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
